---
include:
  - project: ComputeAorta/CI
    file: /templates/submodule.yml

mr-ubuntu:
  tags: [linux]
  image: $CI_REGISTRY/computeaorta/ci/ubuntu:18.04
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
    - ninja -C build

mr-windows:
  tags: [windows]
  image: $CI_REGISTRY/computeaorta/ci/windows:10
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cmd.exe /c '"%ProgramFiles(x86)%\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat"
      && cmake.exe . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
      && ninja -C build'

create-ca-hal-submodule-mr:
  extends: [.create-downstream-submodule-merge-request]
  variables:
    PROJECT: ComputeAorta/ComputeAorta
    GIT_TOKEN: $CA_GIT_WRITE_TOKEN
    API_TOKEN: $CA_GITLAB_API_TOKEN
    SUBMODULE: modules/mux/external/HAL
    SOURCE_BRANCH:
      ${GITLAB_USER_LOGIN}/hal-update-submodule-${CI_COMMIT_SHORT_SHA}
    TARGET_BRANCH: develop
    TITLE: "HAL: Update submodule with latest changes"
