name: Pull Request
on:
  workflow_dispatch:
  pull_request:
    paths:
    - source/**
    - clik/**
    - modules/**
    - examples/**
    - cmake/**
    - hal/**
    - .github/actions/do_build_ock/**
    - .github/actions/setup_ubuntu_build/**
    - .github/workflows/pull_request.yml
    - CMakeLists.txt
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

############### JOB   mr-ubuntu-gcc-x86_64-riscv-fp16-cl3-0-unitcl_vecz:

  mr-ubuntu-gcc-x86_64-riscv-fp16-cl3-0-unitcl_vecz:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.1.0
      with:
        path: code
    - run: cp -R code/.github .github
    - name: setup-ubuntu
      uses: ./.github/actions/setup_ubuntu_build
      with:
        llvm_version: '18'
        llvm_build_type: RelAssert
    - run: echo WORKSPACE is $GITHUB_WORKSPACE && echo PWD is `pwd` && ls -al
    - name: build ock
      uses: ./.github/actions/do_build_ock
      with:
        path: $GITHUB_WORKSPACE/code
        install_dir: $GITHUB_WORKSPACE/install
        build_targets: check-ock-UnitCL-group-vecz
        mux_targets_enable: riscv
        mux_compilers_enable: riscv
        riscv_enabled: ON
        enable_rvv_scalable_vecz_check: ON
        enable_rvv_scalable_vp_vecz_check: ON
        use_linker: gold
        hal_description: RV64GCV_Zfh
        hal_refsi_soc: G1
        hal_refsi_thread_mode: WG
        build_dir: $GITHUB_WORKSPACE/build
        debug_support: ON
        gtest_launcher: "/usr/bin/python;-u;${{ github.workspace }}/code/scripts/gtest-terse-runner.py"
