# Simple workflow for building sccache for PR testing
name: Run ock tests for PR testing
# Note this will currently create a new sscache file and this must be manually pruned until such time as we have a job
# for this.
on:
  pull_request:
    paths:
      - 'source/**'
      - 'modules/**'
      - 'examples/**'
      - 'cmake/**'
      - 'hal/**'
      - '.github/actions/do_build_ock/**'
      - '.github/actions/setup_ubuntu_build/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # build and run host x86_64, execute UnitCL and lit tests and build and run offline
  run_host_x86_64:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # installs tools, ninja, installs llvm and sets up sccahe
      - name: setup-ubuntu
        uses:  ./.github/actions/setup_ubuntu_build
        with:
          llvm_version: 16
          llvm_build_type: RelAssert        
  
      # These need to match the configurations of build_pr_cache to use the cache effectively
      - name: build host x86_64 online release
        uses: ./.github/actions/do_build_ock
        with:
          build_type: Release

      - name: run just online lit
        run:
          ninja -C build check-all-lit

      - name: run host online check
        run:
          ninja -C build check-UnitCL

      # use the previous build for online to get clc
      - name: build host x86_64 offline release
        uses: ./.github/actions/do_build_ock
        with:
          build_type: Release
          extra_flags: -DCA_RUNTIME_COMPILER_ENABLED=OFF -DCA_EXTERNAL_CLC=${{ github.workspace }}/build/bin/clc
          build_dir: build_offline
          build_targets: UnitCL
          assemble_spirv_ll_lit_test_offline: ON

      - name: run host x86_64 offline
        run:
          ninja -C build_offline check-UnitCL

  # build and run riscv m1, execute UnitCL and lit tests
  run_riscv_m1:  

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      # installs tools, ninja, installs llvm and sets up sccahe
      - name: setup-ubuntu
        uses:  ./.github/actions/setup_ubuntu_build
        with:
          llvm_version: 16
          llvm_build_type: RelAssert

      - name: build riscv M1
        uses: ./.github/actions/do_build_ock/do_build_m1  

      - name: run riscv M1 lit
        run:
          ninja -C build check-all-lit

      - name: run riscv M1 UnitCL tests
        run:
          ninja -C build check-UnitCL
